name: 'pipeline_dados'
version: '1.0.0'
config-version: 2

profile: 'pipeline_dados'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  pipeline_dados:
    silver:
      +materialized: view
      +dataset: silver
    gold:
      +materialized: table
      +dataset: gold
